ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Estrategia de solución


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]

=== Decisiones tecnológicas
Para el desarrollo de la aplicación se decidió utilizar las siguientes tecnologías:

* JavaScript será el lenguaje de programación principal.
* React.js para construir interfaces de usuario.
* Node.js para construir el back-end.
* GitHub para el control de versiones.
* Wikidata API para obtener los datos necesarios y poder generar las imagenes y preguntas.
* Empathy API modelo largo de lenguaje (LLM) para ofrecer la posibilidad de obtener pistas de las imagenes de forma conversacional.
* Docker
* Azure

Se ha considerado otras tecnologías para el desarrollo back-end como Spting Boot, pero finalmente se decidió utilizar JavaScript por su enfoque en el desarrollo ágil junto con la facilidad de integración con Node.js y React.js.

=== Descomposición de alto nivel

=== Decisiones para alcanzar objetivos de máxima calidad
[coptions="header",cols ="1,2"]
|===
|Objetivo de calidad | Decisión 
|Usabilidad| 
|Disponibilidad|
|Testabilidad|
|Rendimiento|
|===

=== Decisiones de organización relevantes
El flujo de trabajo se organizará en reuniones semanales, que se llevarán a cabo según sea necesario.
Una de las reuniones se realizará durante la clase de laboratorio y se centrará en decisiones y tareas menores. Las reuniones posteriores se relaizarán de manera remota y estarán dedicadas a deciones mas detalladas y exhaustivas.

Cada tarea asignada, así como problemas encontrados, se documentará como un Issue en GitHub. Además se utilizará GitHub Projects para la organización de las tareas del equipo. 
No habrá una división estricta entre front-end y back-end, todos los miembros del equipo trabajarán en ambas áreas. Parta cada tarea asiganada, se creará una rama específica, y el trabajo realizado se volcará una rama develop mediante pull requests. Una vez que se haya completado una funcionalidad, se fusionará la rama develop con la rama master.